knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
            redirect_route: authentication_google_callback
            redirect_params: {}
        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: authentication_facebook_callback
            redirect_params: {}
            graph_api_version: v3.2
        linkedin:
            type: linkedin
            client_id: '%env(OAUTH_LINKEDIN_ID)%'
            client_secret: '%env(OAUTH_LINKEDIN_SECRET)%'
            redirect_route: authentication_linkedin_callback
            redirect_params: {}